{
    'name': 'Gestion des ressources et des projets de l\'entreprise',
    'version': '1.0.0',
    'sequence': -100,
    'author': 'Fatimazahrae IMLOUL & Oumaima ELHADRAOUI DSE',
    'category': 'Gestionnaire des ressources et des projets',
    'summary': 'Gestion des ressources et des projets de l\'entreprise',
    'description': 'Projet qui a pour but de digitaliser le processus d\'affectation des employés, véhicules et produits aux projets , ainsi que pour la gestion des entrepot et maintenance pour les véhicules',
    'depends': ['base', 'hr', 'hr_contract', 'fleet', 'maintenance', 'sale_management', 'project'],
    'data': [
        'views/employee_view.xml',
        'views/vehicule_view.xml',
        'views/produit_view.xml', 
        'views/projet_view.xml',
        'views/projprod_view.xml',
        'views/projemp_view.xml',  
        'views/projveh_view.xml',  
        'views/entrepot_view.xml',
        'views/ville_view.xml',
        'views/maintenance_view.xml',
        'views/remplacement_view.xml',
        'report/report_employee_template.xml',  
        'report/report_employee_action.xml',
        'report/report_vehicule_template.xml', 
        'report/report_vehicule_action.xml',
        'report/report_produit_template.xml', 
        'report/report_produit_action.xml',
        'report/report_projet_template.xml', 
        'report/report_projet_action.xml', 
        'report/report_projprod_template.xml',  
        'report/report_projprod_action.xml', 
        'report/report_projveh_template.xml', 
        'report/report_projveh_action.xml', 
        'report/report_projemp_template.xml',
        'report/report_projemp_action.xml',
        'report/report_entrepot_template.xml', 
        'report/report_entrepot_action.xml',
        'report/report_ville_template.xml',  
        'report/report_ville_action.xml',
        'report/report_maintenance_template.xml', 
        'report/report_maintenance_action.xml',    
        'report/report_remplacement_template.xml',  
        'report/report_remplacement_action.xml', 
        'security/ir.model.access.csv',


    ],

    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}



